# Use the official PostgreSQL image as a base
FROM postgres

# Set the user working directory inside the container
USER postgres
WORKDIR /app

# Copy the wait-for-postgres script and ensure it's executable
COPY --chown=postgres:postgres ./wait-for-postgres.sh /app/bin/wait-for-postgres.sh
RUN chmod +x ./bin/wait-for-postgres.sh

# Expose PostgreSQL port to the host, to access the container’s services outside.
EXPOSE 5432