@url = localhost:4000
@urlUsers = {{url}}/users
@urlTrails = {{url}}/trails
@urlHikes = {{url}}/hikes

###
POST {{urlUsers}}/create
Content-Type: application/json

{
  "username": "JocaDosSaltos",
  "email": "saltosdotelhado@ohjoca.pt",
  "password": "SaltaJoca123#"
}
> {% if (response.status == 201 ) {
        client.global.set("accessToken", response.body.accessTokenValue);
        client.global.set("refreshToken", response.body.refreshTokenValue);
    }
%}

###
GET {{urlUsers}}/self
Authorization: Bearer {{accessToken}}

###
GET {{urlUsers}}
Authorization: Bearer {{accessToken}}

###
DELETE {{urlUsers}}/logout
Authorization: Bearer {{refreshToken}}

###
POST {{urlUsers}}/login
Content-Type: application/json

{
  "email": "saltosdotelhado@ohjoca.pt",
  "password": "SaltaJoca123#"
}
> {% if (response.status == 201 ) {
        client.global.set("accessToken", response.body.accessTokenValue);
        client.global.set("refreshToken", response.body.refreshTokenValue);
    }
%}

###
PUT {{urlUsers}}/refresh
Authorization: Bearer {{refreshToken}}

> {% if (response.status == 200 ) {
        client.global.set("accessToken", response.body.accessTokenValue);
        client.global.set("refreshToken", response.body.refreshTokenValue);
    }
%}

###
DELETE {{urlUsers}}/delete
Authorization: Bearer {{refreshToken}}