POST localhost:8080/users/create
Content-Type: application/json

{
  "username": "JocaDosSaltos",
  "email": "saltosdotelhado@ohjoca.pt",
  "password": "SaltaJoca123#"
}
> {% client.global.set("token", response.body.tokenValue) %}

###
GET localhost:8080/users/self
Authorization: Bearer {{token}}

###
GET localhost:8080/users
Authorization: Bearer {{token}}

###
DELETE localhost:8080/users/delete
Authorization: Bearer {{token}}