@token = TODO

POST localhost:8080/users/create
Content-Type: application/json

{
  "username": "JocaDosSaltos",
  "email": "saltosdotelhado@ohjoca.pt",
  "password": "SaltaJoca123"
}

###
GET localhost:8080/users/self
Authorization: {{token}}

###
GET localhost:8080/users
Accept: application/json

###
DELETE localhost:8080/users/delete
Authorization: {{token}}