classDiagram
    class UserRank {
        <<enumeration>>
        NEW
        VERIFIED
    }

    class User {
        +String username
        +String email
        +String passwordValidInfo
        +UserRank rank
        +int completedTrails
        +double totalKmHiked
        +long totalHikingTime
    }

    User *-- UserRank

    class Token {
        +String username
        +String validationInfo
        +kotlin.Instant lastUse
    }

    User --o Token

